version: "3.9"
services:
  db:
    image: postgres:15
    container_name: collectify_test_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: my_test_db
    ports:
      - "5432:5432"

  db2:
    image: postgres:15
    container_name: collectify_local
    environment:
      POSTGRES_USER: myuser2
      POSTGRES_PASSWORD: mypass2
      POSTGRES_DB: my_test_db2
    ports:
      - "5433:5432"
